"use client";
import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";

type OrderItem={id:number;product_name:string;color?:string;size?:string;quantity:number;unit_price:number};
type Order={id:string;order_number:string;customer_name:string;phone:string;email:string;delivery_method:string;delivery_address:string;note:string;subtotal:number;status:string;created_at:string;order_items:OrderItem[]};
const statuses=["待確認","待付款","已付款","已出貨","完成","取消"];

export default function OrdersPage(){
  const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState("");
  const load=async()=>{const {data,error}=await supabase.from("orders").select("*, order_items(*)").order("created_at",{ascending:false});if(error)console.error(error);else setOrders(data||[]);setLoading(false)};
  useEffect(()=>{load()},[]);
  const updateStatus=async(id:string,status:string)=>{setSaving(id);const {error}=await supabase.from("orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);setSaving("");if(error)return alert(`更新失敗：${error.message}`);setOrders((current)=>current.map((order)=>order.id===id?{...order,status}:order))};
  return <main className="px-6 py-12"><div className="mx-auto max-w-6xl"><p className="text-sm tracking-[.25em] text-orange-500">ORDERS</p><h1 className="mt-3 text-4xl font-bold">訂單管理</h1>{loading?<p className="mt-10 text-zinc-500">讀取訂單中…</p>:!orders.length?<div className="mt-10 rounded-3xl border border-white/10 bg-[#1a1a1a] p-10 text-center text-zinc-500">目前還沒有訂單</div>:<div className="mt-10 space-y-6">{orders.map((order)=><article key={order.id} className="rounded-3xl border border-white/10 bg-[#1a1a1a] p-6"><div className="flex flex-col justify-between gap-5 md:flex-row"><div><p className="text-sm text-orange-400">{order.order_number}</p><h2 className="mt-2 text-2xl font-bold">{order.customer_name}</h2><p className="mt-2 text-sm text-zinc-500">{new Date(order.created_at).toLocaleString("zh-TW")}</p></div><div><label className="text-xs text-zinc-500">訂單狀態</label><select value={order.status} disabled={saving===order.id} onChange={(e)=>updateStatus(order.id,e.target.value)} className="mt-2 block rounded-xl border border-white/10 bg-[#111] px-4 py-3">{statuses.map((status)=><option key={status}>{status}</option>)}</select></div></div><div className="mt-6 grid gap-5 border-t border-white/10 pt-6 md:grid-cols-2"><div className="space-y-2 text-sm text-zinc-300"><p>{order.phone}</p><p>{order.email}</p><p>{order.delivery_method}</p><p>{order.delivery_address}</p>{order.note&&<p className="text-zinc-500">備註：{order.note}</p>}</div><div className="space-y-3">{order.order_items.map((item)=><div key={item.id} className="flex justify-between gap-4 text-sm"><span>{item.product_name} {[item.color,item.size].filter(Boolean).join(" / ")} × {item.quantity}</span><strong>NT$ {(item.unit_price*item.quantity).toLocaleString()}</strong></div>)}<div className="flex justify-between border-t border-white/10 pt-3 text-lg"><span>商品小計</span><strong className="text-orange-400">NT$ {order.subtotal.toLocaleString()}</strong></div></div></div></article>)}</div>}</div></main>;
}
