"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";

type MemberOrder = { id:string; order_number:string; status:string; subtotal:number; created_at:string };
type Member = { id:string; email:string; full_name:string; phone:string; default_delivery:string; default_address:string; created_at:string; orders:MemberOrder[] };

export default function AdminMembersPage() {
  const [members,setMembers]=useState<Member[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [open,setOpen]=useState("");
  useEffect(()=>{const load=async()=>{const {data,error}=await supabase.from("member_profiles").select("id,email,full_name,phone,default_delivery,default_address,created_at,orders(id,order_number,status,subtotal,created_at)").eq("role","member").order("created_at",{ascending:false}); if(error)console.error(error); else setMembers((data as Member[])||[]); setLoading(false);};load();},[]);
  const shown=useMemo(()=>{const key=query.trim().toLowerCase(); return !key?members:members.filter(m=>[m.full_name,m.email,m.phone].some(v=>(v||"").toLowerCase().includes(key)));},[members,query]);
  return <main className="px-6 py-12"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold tracking-[.25em] text-orange-500">MEMBERS</p><h1 className="mt-3 text-4xl font-bold">會員管理</h1><div className="mt-8 flex flex-wrap items-center justify-between gap-4"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋姓名、手機或 Email" className="w-full max-w-md rounded-xl border border-white/15 bg-[#1a1a1a] px-4 py-3 outline-none"/><p className="text-sm text-zinc-500">共 {members.length} 位會員</p></div>{loading?<p className="mt-10 text-zinc-500">讀取會員中…</p>:<div className="mt-8 space-y-4">{shown.map(member=><article key={member.id} className="rounded-3xl border border-white/10 bg-[#1a1a1a] p-6"><button type="button" onClick={()=>setOpen(open===member.id?"":member.id)} className="flex w-full items-start justify-between gap-5 text-left"><div><h2 className="text-xl font-bold">{member.full_name||"尚未填寫姓名"}</h2><p className="mt-2 text-sm text-zinc-400">{member.phone||"未填手機"} · {member.email}</p><p className="mt-2 text-xs text-zinc-600">加入時間：{new Date(member.created_at).toLocaleString("zh-TW")}</p></div><div className="text-right"><strong className="text-2xl text-orange-400">{member.orders?.length||0}</strong><p className="text-xs text-zinc-500">筆訂單</p></div></button>{open===member.id&&<div className="mt-6 grid gap-6 border-t border-white/10 pt-6 md:grid-cols-[280px_1fr]"><div className="space-y-2 text-sm text-zinc-300"><p>常用配送：{member.default_delivery}</p><p>常用地址：{member.default_address||"尚未填寫"}</p></div><div>{!member.orders?.length?<p className="text-sm text-zinc-500">這位會員目前沒有訂單。</p>:<div className="space-y-3">{member.orders.map(order=><div key={order.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#111] p-4"><div><strong className="text-orange-400">{order.order_number}</strong><p className="mt-1 text-xs text-zinc-500">{new Date(order.created_at).toLocaleString("zh-TW")}</p></div><div className="text-right"><strong>{order.status}</strong><p className="mt-1 text-sm">NT$ {Number(order.subtotal).toLocaleString()}</p></div></div>)}</div>}</div></div>}</article>)}</div>}</div></main>;
}
