create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_sort_idx on public.product_images(product_id, sort_order, id);
alter table public.product_images enable row level security;
drop policy if exists "public read product images" on public.product_images;
create policy "public read product images" on public.product_images for select to anon, authenticated using (true);
drop policy if exists "authenticated manage product images" on public.product_images;
create policy "authenticated manage product images" on public.product_images for all to authenticated using (true) with check (true);
