-- Run this migration in Supabase SQL Editor.
-- Existing products remain intact: category defaults to 鞋類 and legacy size/stock stay usable.

alter table public.products
  add column if not exists category text;

update public.products
set category = '鞋類'
where category is null or btrim(category) = '';

alter table public.products
  alter column category set default '鞋類',
  alter column category set not null;

alter table public.products
  drop constraint if exists products_category_check;

alter table public.products
  add constraint products_category_check
  check (category in ('鞋類', '服飾', '其他'));

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  color text not null,
  size text not null,
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now(),
  constraint product_variants_product_color_size_key unique (product_id, color, size),
  constraint product_variants_color_not_blank check (btrim(color) <> ''),
  constraint product_variants_size_not_blank check (btrim(size) <> '')
);

create index if not exists product_variants_product_id_idx
  on public.product_variants(product_id);

alter table public.product_variants enable row level security;

drop policy if exists "Anyone can read product variants" on public.product_variants;
create policy "Anyone can read product variants"
  on public.product_variants for select
  using (true);

drop policy if exists "Authenticated users can insert product variants" on public.product_variants;
create policy "Authenticated users can insert product variants"
  on public.product_variants for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update product variants" on public.product_variants;
create policy "Authenticated users can update product variants"
  on public.product_variants for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete product variants" on public.product_variants;
create policy "Authenticated users can delete product variants"
  on public.product_variants for delete
  to authenticated
  using (true);
