create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_name text not null,
  phone text not null,
  email text not null,
  delivery_method text not null check (delivery_method in ('宅配', '7-ELEVEN 店到店', '全家店到店')),
  delivery_address text not null,
  note text not null default '',
  subtotal numeric(12, 0) not null check (subtotal >= 0),
  status text not null default '待確認' check (status in ('待確認', '待付款', '已付款', '已出貨', '完成', '取消')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  variant_id bigint references public.product_variants(id),
  product_name text not null,
  color text,
  size text,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 0) not null check (unit_price >= 0)
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "authenticated users manage orders" on public.orders;
create policy "authenticated users manage orders" on public.orders for all to authenticated using (true) with check (true);
drop policy if exists "authenticated users manage order items" on public.order_items;
create policy "authenticated users manage order items" on public.order_items for all to authenticated using (true) with check (true);

create or replace function public.place_order(p_customer jsonb, p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id uuid;
  new_order_number text;
  computed_subtotal numeric(12,0) := 0;
  item jsonb;
  product_record record;
  variant_record record;
  item_quantity integer;
  item_variant_id bigint;
begin
  if jsonb_array_length(p_items) = 0 then raise exception '購物車沒有商品'; end if;
  if coalesce(p_customer->>'name','') = '' or coalesce(p_customer->>'phone','') = '' or coalesce(p_customer->>'email','') = '' or coalesce(p_customer->>'address','') = '' then raise exception '訂購資料不完整'; end if;
  if (p_customer->>'delivery') not in ('宅配', '7-ELEVEN 店到店', '全家店到店') then raise exception '配送方式不正確'; end if;

  for item in select * from jsonb_array_elements(p_items) loop
    item_quantity := (item->>'quantity')::integer;
    if item_quantity < 1 then raise exception '商品數量不正確'; end if;
    select id, name, price, category, stock, size into product_record from public.products where id = (item->>'product_id')::bigint;
    if not found then raise exception '商品不存在'; end if;
    item_variant_id := nullif(item->>'variant_id','')::bigint;
    if product_record.category = '服飾' then
      select id, color, size, stock into variant_record from public.product_variants where product_id = product_record.id and ((item_variant_id is not null and id = item_variant_id) or (item_variant_id is null and color = item->>'color' and size = item->>'size')) limit 1;
      if not found or variant_record.stock < item_quantity then raise exception '商品規格庫存不足'; end if;
      item_variant_id := variant_record.id;
    elsif product_record.stock < item_quantity then raise exception '商品庫存不足'; end if;
    computed_subtotal := computed_subtotal + product_record.price * item_quantity;
  end loop;

  new_order_number := 'GS' || to_char(now(), 'YYMMDDHH24MISS') || upper(substr(gen_random_uuid()::text, 1, 4));
  insert into public.orders (order_number, customer_name, phone, email, delivery_method, delivery_address, note, subtotal)
  values (new_order_number, p_customer->>'name', p_customer->>'phone', p_customer->>'email', p_customer->>'delivery', p_customer->>'address', coalesce(p_customer->>'note',''), computed_subtotal)
  returning id into new_order_id;

  for item in select * from jsonb_array_elements(p_items) loop
    select id, name, price, category, stock, size into product_record from public.products where id = (item->>'product_id')::bigint;
    item_variant_id := nullif(item->>'variant_id','')::bigint;
    if product_record.category = '服飾' then
      select id, color, size, stock into variant_record from public.product_variants where product_id = product_record.id and ((item_variant_id is not null and id = item_variant_id) or (item_variant_id is null and color = item->>'color' and size = item->>'size')) limit 1;
      item_variant_id := variant_record.id;
      insert into public.order_items (order_id, product_id, variant_id, product_name, color, size, quantity, unit_price)
      values (new_order_id, product_record.id, item_variant_id, product_record.name, variant_record.color, variant_record.size, (item->>'quantity')::integer, product_record.price);
    else
      insert into public.order_items (order_id, product_id, variant_id, product_name, color, size, quantity, unit_price)
      values (new_order_id, product_record.id, null, product_record.name, null, product_record.size, (item->>'quantity')::integer, product_record.price);
    end if;
  end loop;

  return jsonb_build_object('id', new_order_id, 'order_number', new_order_number, 'subtotal', computed_subtotal);
end;
$$;

revoke all on function public.place_order(jsonb, jsonb) from public;
grant execute on function public.place_order(jsonb, jsonb) to anon, authenticated;
